### ISSUE TITLE
Mention in the task comment which SAL is being used

### ISSUE THREAD

**Issue by greggrossmeier** [bd808/tools-stashbot#14]
The use case is probably mostly Beta Cluster vs Production for us. Some things are applied in Beta first and then prod and are !log'd. It be nice if the comment on the task said something like "Mentioned in SAL (#wikimedia-releng) [timestamp] blahdeblah"

**Comment by bd808** [comment]
This can actually be done in configuration by adding `%(channel)s` to the phabricator message template.

``` yaml
sal:
  phab: "{nav icon=file, name=Mentioned in SAL (%(channel)s), href=%(href)s} [%(@timestamp)s] <%(nick)s> %(message)s"
```

**Comment by bd808** [comment]
`{{done}}` -- https://phabricator.wikimedia.org/T108720#2631556

**Comment by greggrossmeier** [comment]
<3
