### ISSUE TITLE
Feature request: Task lookup by mentioning a task in channel

### ISSUE THREAD

**Issue by 20after4** [bd808/tools-stashbot#5]
The inverse of #4: when Tn is mentioned in IRC, bot posts a link (and title) of the task into the channel.

This is a built in feature of phabricator (phabbot) but we don't currently use phabbot and it seems redundant to activate yet another bot. So lets re-invent a wheel instead!

**Comment by bd808** [comment]
Irc messages from phabbot look like:
```
[13:48:38] <staticshock> ah, i found T1191
[13:48:39] <phabot> T1191: Comments are truncated at first non-base-plane character - https://secure.phabricator.com/T1191
```
In my [Textual theme](https://github.com/bd808/Textual-Theme-bd808) I check for Phab links with this regex:
```
RE_PHAB = /([^/])\b([TMP]\d+)\b/g
```
The `[^/]` is in there to guard against linking when the Tnnnn is already part of a URL.

**Comment by bd808** [comment]
Fixed!
